**Tensors in PyTorch** are multi-dimensional arrays that are **similar to NumPy arrays** but with additional capabilities for GPU acceleration. They are the fundamental building blocks for creating and training neural networks in PyTorch. Tensors can be created in various ways, including from lists, NumPy arrays, or by using built-in functions that generate tensors with specific properties (like random values, zeros, or ones).

In [9]:
# Check PyTorch installation and CUDA availability
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())

2.5.1
CUDA available: False


# Creating tensors in PyTorch

In [10]:
# Empty Tensor 
a = torch.empty(3,4)
print(a)
type(a)

tensor([[-1.1072e+20,  9.6690e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


torch.Tensor

In [11]:
# Ones Tensor
b = torch.ones(2,3)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
# Zeros Tensor
c = torch.zeros(4,5)
print(c)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [14]:
# Radom Tensor
d = torch.rand(2,2)
print(d)

tensor([[0.1252, 0.4537],
        [0.1113, 0.4372]])


In [15]:
# Seed for reproducibility
torch.manual_seed(42)
# Random Tensor with seed
e = torch.rand(2,2)
print(e)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])


In [19]:
# Identity Matrix
f = torch.eye(3)
print(f)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# Tensor Shapes

In [ ]:

x = torch.tensor([[1, 2], [3, 4]])
print(x)

tensor([[1, 2],
        [3, 4]])


In [23]:
x.shape

torch.Size([2, 2])

In [25]:
torch.empty_like(x)

tensor([[0, 0],
        [0, 0]])

In [26]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0]])

In [27]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1]])

In [28]:
torch.randn_like(x, dtype=torch.float64)

tensor([[ 0.2345,  0.2303],
        [-1.1229, -0.1863]], dtype=torch.float64)

# Tensors Data Types

In [ ]:
# checking data type of tensor
x.dtype

torch.int64

In [30]:
# assigning data type to tensor
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
y.dtype

torch.float64

In [31]:
# assigning data type to tensor
z = torch.tensor([[1.0, 2.2], [3.4, 4.1]], dtype=torch.int32)
z.dtype

torch.int32

In [32]:
x.to(torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

# Mathematical Operations on Tensors

# Scalar Operations

In [33]:
a = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [40]:
# Addition
a + 10
# Subtraction
a - 2
# Multiplication
a * 3
# Division
a / 2
# Exponentiation
a ** 2
# Modulus
a % 2

tensor([[1, 0, 1],
        [0, 1, 0]])

# Element-wise Operations

In [42]:
f = torch.tensor([[1.4, 2.4], [3.7, 4.0]])
g = torch.tensor([[5.0, 6.1], [7.2, 8.3]])
print(f)
print(g)

tensor([[1.4000, 2.4000],
        [3.7000, 4.0000]])
tensor([[5.0000, 6.1000],
        [7.2000, 8.3000]])


In [43]:
# Addition
f + g
# Subtraction
f - g
# Multiplication
f * g
# Division
f / g


tensor([[0.2800, 0.3934],
        [0.5139, 0.4819]])

In [44]:
# Absolute Value
torch.abs(f)
# Square Root
torch.sqrt(f)
# Exponential
torch.exp(f)
# round
torch.round(f)
# ceil
torch.ceil(f)
# floor
torch.floor(f)
# clamp
torch.clamp(f, min=2.0, max=3.5)

tensor([[2.0000, 2.4000],
        [3.5000, 3.5000]])

# Comparison Operations

In [49]:
a = torch.randint(size=(2, 3), low=0, high=10)
b = torch.randint(size=(2, 3), low=1, high=10)
print(a)
print(b)

tensor([[9, 6, 2],
        [0, 6, 2]])
tensor([[2, 4, 4],
        [9, 6, 5]])


In [ ]:
# equal
a == b
# greater than
a > b
# less than
a < b
# not equal
a != b
# greater than or equal to
a >= b
# less than or equal to
a <= b

tensor([[False, False,  True],
        [ True,  True,  True]])

# Copying a tensor

In [57]:
j = torch.randint(size=(2, 3), low=0, high=10)
j

tensor([[6, 9, 5],
        [4, 8, 8]])

In [60]:
# copying a tensor
k = j.clone()
k

tensor([[6, 9, 5],
        [4, 8, 8]])

In [61]:
id(k) == id(j)

False

# Converting Between NumPy & PyTorch Tensors

In [62]:
import numpy as np

np_array = np.array([1,2,3])
torch_tensor = torch.from_numpy(np_array)

torch_tensor.numpy()


array([1, 2, 3])

# Reshaping Tensors

In [65]:
x = torch.ones(4, 4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
x.reshape(2, 8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
x.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
x.unsqueeze(0).shape

torch.Size([1, 4, 4])