# Simple NN Pipeline

In [1]:
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self, num_feat):
        super().__init__()
        self.fc1 = nn.Linear(num_feat, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.fc1(features)    
        out = self.sigmoid(out)
        return out    

In [2]:
features = torch.rand(10,5)
features

tensor([[0.3256, 0.6726, 0.6759, 0.4806, 0.9589],
        [0.2244, 0.7362, 0.6924, 0.5255, 0.2442],
        [0.7216, 0.8464, 0.1138, 0.3006, 0.8847],
        [0.8237, 0.9617, 0.1227, 0.7693, 0.8435],
        [0.0137, 0.1106, 0.6049, 0.8050, 0.0196],
        [0.0642, 0.4959, 0.9116, 0.6452, 0.4273],
        [0.9529, 0.4005, 0.4241, 0.1252, 0.9617],
        [0.4826, 0.4786, 0.4827, 0.1071, 0.6620],
        [0.9663, 0.5779, 0.3273, 0.2021, 0.0168],
        [0.0456, 0.8896, 0.5142, 0.6952, 0.5960]])

In [3]:
model = SimpleNN(features.shape[1])
model(features)

tensor([[0.6336],
        [0.5783],
        [0.6026],
        [0.6398],
        [0.6253],
        [0.6193],
        [0.6423],
        [0.5944],
        [0.5674],
        [0.5958]], grad_fn=<SigmoidBackward0>)

In [4]:
model.fc1.weight


Parameter containing:
tensor([[ 0.1863, -0.3187,  0.0994,  0.3995,  0.2974]], requires_grad=True)

In [5]:
model.fc1.bias

Parameter containing:
tensor([0.1572], requires_grad=True)

# Complex Code Example

In [6]:
import torch 
import torch.nn as nn
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.NeuralNetwork = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self, features):
        Output = self.NeuralNetwork(features)    
        return Output

In [7]:
features = torch.rand(10,5)
model = Model(features.shape[1])
model(features)

tensor([[0.3813],
        [0.4452],
        [0.4130],
        [0.4379],
        [0.4494],
        [0.4055],
        [0.3501],
        [0.4261],
        [0.3880],
        [0.3763]], grad_fn=<SigmoidBackward0>)