In [2]:
import torch.nn as nn
from sklearn.datasets import make_classification
import torch

In [4]:
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [5]:
X.shape, y.shape

((10, 2), (10,))

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [9]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [10]:
from torch.utils.data import Dataset, DataLoader

In [11]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels 

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [12]:
dataset = CustomDataset(X, y)
len(dataset)

10

In [13]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [15]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("---")

tensor([[-0.7206, -0.9606],
        [ 1.0683, -0.9701],
        [ 1.8997,  0.8344],
        [-1.1402, -0.8388]])
tensor([0, 1, 1, 0])
---
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858],
        [-2.8954,  1.9769],
        [ 1.7774,  1.5116]])
tensor([0, 1, 0, 1])
---
tensor([[-0.9382, -0.5430],
        [-1.9629, -0.9923]])
tensor([1, 0])
---
